# Generated by Django 5.0.14 on 2025-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('username', 'platform')},
        ),
    ]
