# Generated by Django 5.0.14 on 2025-09-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_blog_profile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='platform',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('GitHub', 'GitHub'), ('Instagram', 'Instagram')], max_length=100),
        ),
    ]
