# Generated by Django 5.0.14 on 2025-09-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tiktok_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tiktok_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='private_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='tiktok_bio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='tiktok_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='videos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='platform',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('GitHub', 'GitHub'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok')], max_length=100),
        ),
    ]
