# Generated by Django 5.0.14 on 2025-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_tiktok_created_at_profile_tiktok_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
