# Generated by Django 5.0.14 on 2025-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_post_options_alter_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
