# Generated by Django 5.0.14 on 2025-10-13 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_posts_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_post_time', models.CharField(blank=True, max_length=50, null=True)),
                ('most_active_days', models.JSONField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('top_keywords', models.JSONField(blank=True, null=True)),
                ('geo_locations', models.JSONField(blank=True, null=True)),
                ('network_size', models.IntegerField(blank=True, null=True)),
                ('network_density', models.FloatField(blank=True, null=True)),
                ('interests', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_analysis', to='profiles.profile')),
            ],
            options={
                'verbose_name_plural': 'Behavioral Analyses',
            },
        ),
    ]
