# Generated by Django 5.0.14 on 2025-11-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_rawpost_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
