# Generated by Django 5.0.14 on 2025-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_socialmediaaccount_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts_count',
        ),
        migrations.AlterField(
            model_name='rawpost',
            name='platform',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('GitHub', 'GitHub'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok')], max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='platform',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('GitHub', 'GitHub'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok')], max_length=100),
        ),
    ]
